---

kind: pipeline
type: exec
name: Run E2E tests

node:
  os: linux
  arch: amd64

steps:
  - name: test
    commands:
      - go mod download
      - export CI_CATALYST_TEST_IMAGE="${DRONE_REPO}:${DRONE_BUILD_NUMBER}"
      - docker build --tag "$CI_CATALYST_TEST_IMAGE" --build-arg=GIT_VERSION="$(git describe --always --long --abbrev=8 --dirty)" .
      - go test -v ./test/e2e/e2e_test.go --image "$CI_CATALYST_TEST_IMAGE" --network "catalyst-test-${DRONE_BUILD_NUMBER}"

trigger:
  event:
    - push
