[http]
  [http.routers]
    [http.routers.api]
      entryPoints = ["web"]
      service = "service-api"
      rule = "PathPrefix(`/api`)"
      priority = 10

    [http.routers.mist]
      entryPoints = ["web"]
      service = "service-mist"
      rule = "PathPrefix(`/hls`)"
      priority = 5

    [http.routers.www]
      entryPoints = ["web"]
      service = "service-www"
      rule = "PathPrefix(`/`)"
      priority = 5

  # Add the service
  [http.services]
    [http.services.service-api]
      [http.services.service-api.loadBalancer]
        [[http.services.service-api.loadBalancer.servers]]
          url = "http://localhost:3004/"

    [http.services.service-mist]
      [http.services.service-mist.loadBalancer]
        [[http.services.service-mist.loadBalancer.servers]]
          url = "http://localhost:8081/"

    [http.services.service-www]
      [http.services.service-www.loadBalancer]
        [[http.services.service-www.loadBalancer.servers]]
          url = "http://localhost:5000/"
