[http]
  [http.routers]
    [http.routers.api]
      entryPoints = ["web"]
      service = "service-api"
      rule = "PathPrefix(`/api`)"
      priority = 10

    [http.routers.data]
      entryPoints = ["web"]
      service = "service-data"
      rule = "PathPrefix(`/data`)"
      priority = 10

    [http.routers.www]
      entryPoints = ["web"]
      service = "service-www"
      rule = "PathPrefix(`/`)"
      priority = 5

  # Add the service
  [http.services]
    [http.services.service-api]
      [http.services.service-api.loadBalancer]
        [[http.services.service-api.loadBalancer.servers]]
          url = "http://localhost:3004/"

    [http.services.service-data]
      [http.services.service-data.loadBalancer]
        [[http.services.service-data.loadBalancer.servers]]
          url = "http://localhost:8082/"

    [http.services.service-www]
      [http.services.service-www.loadBalancer]
        [[http.services.service-www.loadBalancer.servers]]
          url = "http://localhost:3012/"
