global:
  scrape_interval: 5s
scrape_configs:
  - job_name: livepeer
    static_configs:
      - targets:
          - localhost:4242
          - localhost:7935
          - localhost:7936
          - localhost:8008
          - localhost:3004
